"""Add Refund model

Revision ID: 0b7525938a8a
Revises: 813abd98079c
Create Date: 2026-01-13 16:03:07.119030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7525938a8a'
down_revision = '813abd98079c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suborder_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('DEFECTIVE', 'WRONG_PRODUCT', 'NOT_AS_DESCRIBED', 'OTHER', name='refundreason'), nullable=False),
    sa.Column('reason_details', sa.Text(), nullable=False),
    sa.Column('evidence_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', name='refundstatus'), nullable=False),
    sa.Column('admin_decision_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('refund_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['suborder_id'], ['suborders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refunds_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_suborder_id'), ['suborder_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_suborder_id'))
        batch_op.drop_index(batch_op.f('ix_refunds_customer_id'))

    op.drop_table('refunds')
    # ### end Alembic commands ###
